### ISSUE TITLE
Error Patching

### ISSUE THREAD

**Issue by MrVash** [ReaperAnon/True-Unleveled-Skyrim#1]
When attempting to patch, received error each time. Moved the patcher on top above others but the same thing occurs. 
In settings, have 'Unlevel Game' and 'Zones' options checked. All else is unchecked.

Log below:

Extra data folder already exists. Leaving as is: G:\SteamLibrary\steamapps\common\SSE Tools\Synthesis\Data\True-Unleveled-Skyrim
Compiling
(C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Git\2gzbtc2m.nl5\Runner\TrueUnleveledSkyrim): dotnet build --runtime win-x64 "TrueUnleveledSkyrim.csproj" -c Release
Compiled
Sha f5fe89e44e62aa439f9c9e6735798ed9433e811d
(): dotnet run --project "C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Git\2gzbtc2m.nl5\Runner\TrueUnleveledSkyrim\TrueUnleveledSkyrim.csproj" -c Release --runtime win-x64 --no-build check-runnability --DataFolderPath "G:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Workspace\Plugins.txt
Running
(): dotnet run --project "C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Git\2gzbtc2m.nl5\Runner\TrueUnleveledSkyrim\TrueUnleveledSkyrim.csproj" --runtime win-x64 --no-build -c Release run-patcher --DataFolderPath "G:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "G:\SteamLibrary\steamapps\common\SSE Tools\Synthesis\Data\True-Unleveled-Skyrim" --DefaultDataFolderPath C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Git\2gzbtc2m.nl5\Runner\TrueUnleveledSkyrim\Data --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Workspace\Plugins.txt --OutputPath "C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Workspace\0 - True-Unleveled-Skyrim" --PatcherName True-Unleveled-Skyrim --PersistencePath C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Persistence
Mutagen version: 0.31
Mutagen sha: cf708daf0b89c643b94bf08c28e7ab2a719d9451
Synthesis version: 0.19.3
Synthesis sha: e765ef1333b34f3ded15de6ed5ec18983ee48c36
run-patcher --DataFolderPath "G:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "G:\SteamLibrary\steamapps\common\SSE Tools\Synthesis\Data\True-Unleveled-Skyrim" --DefaultDataFolderPath C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Git\2gzbtc2m.nl5\Runner\TrueUnleveledSkyrim\Data --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Workspace\Plugins.txt --OutputPath "C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Workspace\0 - True-Unleveled-Skyrim" --PatcherName True-Unleveled-Skyrim --PersistencePath C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Persistence
Prepping state.
Using TextFileSharedFormKeyAllocator allocator
Reading settings: G:\SteamLibrary\steamapps\common\SSE Tools\Synthesis\Data\True-Unleveled-Skyrim\settings.json
System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\SteamLibrary\steamapps\common\SSE Tools\Synthesis\Data\Skyrim Special Edition\True-Unleveled-Skyrim\artifactKeys.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at TrueUnleveledSkyrim.Config.JsonHelper.LoadConfig[T](String configPath) in C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Git\2gzbtc2m.nl5\Runner\TrueUnleveledSkyrim\Config\JsonHelper.cs:line 11
   at TrueUnleveledSkyrim.Patch.LeveledItemsPatcher.PatchLVLI(IPatcherState`2 state) in C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Git\2gzbtc2m.nl5\Runner\TrueUnleveledSkyrim\Patch\LeveledItems.cs:line 196
   at TrueUnleveledSkyrim.Patcher.RunPatch(IPatcherState`2 state) in C:\Users\Home-AI\AppData\Local\Temp\Synthesis\twaiijkc.jp0\Git\2gzbtc2m.nl5\Runner\TrueUnleveledSkyrim\Program.cs:line 36
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 94
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 456
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 404
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 378
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)

**Comment by ReaperAnon** [comment]
Was because you used an older version of Synthesis. I had a hardcoded filepath for the configs for the test release, changed it for the actual release now.
