### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Zazanels** [ReaperAnon/True-Unleveled-Skyrim#10]
Mutagen.Bethesda.Plugins.Exceptions.TooManyMastersException: Synthesis True-Unleveled-Skyrim.esp has too many masters on masters list. 293 >= 254.
   at Mutagen.Bethesda.Plugins.Masters.MasterReferenceCollection.SetTo(IEnumerable`1 masters)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.ConstructWriteMasters(IModGetter mod)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.PostProcessAdjustments(MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.WriteHeader(BinaryWriteParameters param, MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModCommon.WriteParallel(ISkyrimModGetter item, Stream stream, BinaryWriteParameters param, ParallelWriteParameters parallelParam, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.WriteToBinaryParallel(ISkyrimModGetter item, String path, BinaryWriteParameters param, ParallelWriteParameters parallelParam, IFileSystem fileSystem)
   at Mutagen.Bethesda.Skyrim.SkyrimMod.Mutagen.Bethesda.Plugins.Records.IModGetter.WriteToBinaryParallel(FilePath path, BinaryWriteParameters param, IFileSystem fileSystem, ParallelWriteParameters parallelWriteParams)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 641
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass45_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 496
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 881
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 484
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass44_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 456

**Comment by ReaperAnon** [comment]
It's telling you the issue right on the first line, the plugin has too many master files. The maximum is 254.
If it depends on too many other mods it won't work. Read up on groups in Synthesis and make multiple groups with copies of the patcher. Only run one part of the patcher in each, like the NPC module, the item module, etc.
Should work that way unless you simply have too many mods.
