### ISSUE TITLE
TUS throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by PinoyBloon** [ReaperAnon/True-Unleveled-Skyrim#11]
```
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim] System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim]    at Mutagen.Bethesda.Skyrim.NpcBinaryOverlay.get_NAM5()
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim]    at Mutagen.Bethesda.Skyrim.NpcSetterTranslationCommon.DeepCopyIn(INpc item, INpcGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim]    at Mutagen.Bethesda.Skyrim.NpcSetterTranslationCommon.DeepCopy(INpcGetter item, TranslationMask copyMask)
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim]    at TrueUnleveledSkyrim.Patch.NPCsPatcher.PatchNPCs(IPatcherState`2 state) in C:\Users\Admin\AppData\Local\Temp\Synthesis\z41m2est.i3d\Git\jl1djgzz.xtu\Runner\TrueUnleveledSkyrim\Patch\NPCs.cs:line 914
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim]    at TrueUnleveledSkyrim.Patcher.RunPatch(IPatcherState`2 state) in C:\Users\Admin\AppData\Local\Temp\Synthesis\z41m2est.i3d\Git\jl1djgzz.xtu\Runner\TrueUnleveledSkyrim\Program.cs:line 46
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass16_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 106
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim] --- End of stack trace from previous location ---
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 631
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass45_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 496
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim] --- End of stack trace from previous location ---
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 885
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 484
[39.2][Skyrim Special Edition][True-Unleveled-Skyrim]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass44_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 456
[39.2][True-Unleveled-Skyrim][Skyrim Special Edition] Error while running
[39.2][Skyrim Special Edition] Finished patcher run

```

Here's the complete log

[Everything.txt](https://github.com/user-attachments/files/15949275/Everything.txt)

**Comment by PinoyBloon** [comment]
Resolved by tinkering myself. Turns out the problematic esp is Purist Vanilla. Disabled it, and then the patcher is running smooth
