### ISSUE TITLE
patcher keeps spitting errors

### ISSUE THREAD

**Issue by khirasier** [ReaperAnon/True-Unleveled-Skyrim#8]
the patcher keeps spitting out this error for me

 ---> (Inner Exception #17) RecordException 3DNPC0.esp => : The type initializer for 'Mutagen.Bethesda.Plugins.Records.ModInstantiator`1' threw an exception. System.TypeInitializationException: The type initializer for 'Mutagen.Bethesda.Plugins.Records.ModInstantiator`1' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Linq.Expressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Linq.Expressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Mutagen.Bethesda.Plugins.Records.ModInstantiatorReflection.GetActivator[TMod](ILoquiRegistration regis)
   at Mutagen.Bethesda.Plugins.Records.ModInstantiator`1..cctor()
   --- End of inner exception stack trace ---
   at Mutagen.Bethesda.Plugins.Records.DI.ModImporter`1.Import(ModPath modPath, StringsReadParameters stringsParam)
   at Mutagen.Bethesda.Plugins.Order.DI.LoadOrderImporter`1.<>c__DisplayClass9_0.<Import>b__0(ILoadOrderListingGetter listing, ParallelLoopState _, Int64 modIndex)   at Mutagen.Bethesda.Plugins.Order.DI.LoadOrderImporter`1.<>c__DisplayClass9_0.<Import>b__0(ILoadOrderListingGetter listing, ParallelLoopState _, Int64 modIndex)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
   
   thats just one esp, it will spit this same error out for quite a few, but i dont think its anything wrong with the mods cause 2 of the esps it spits this error for is actually the skyrim.esm and update.esm

i was thinking maybe it cant read the new 1.71 esp format but i feel like if that was the case no synthesis patches would work but all the others i use work fine

**Comment by BooLTonian** [comment]
This looks like your installation of the .NET SDK is the issue.

On the installation page of Synthesis it links you to the microsoft website that it wants you to install from. (https://dotnet.microsoft.com/en-us/download) If you just hit the first download button you saw, it would've given you the SDK for .NET 8, but you need .NET 7. Since .NET 8 fully released in November, I guess the Synthesis people haven't updated that link.
The link you need is https://dotnet.microsoft.com/en-us/download/dotnet/7.0
On this page, you should probably download the x64, unless you have a 32-bit OS, then you would use the x86 download. If you don't know whether your OS is 32 bit or not, it probably isn't, but you could look up how to check. After installing, restart your computer.

Alternatively, you might have just not restarted your computer since whenever you installed the .NET SDK.

Synthesis also has a FAQ for if your patching doesn't work after installing the .NET SDK:
https://github.com/Mutagen-Modding/Synthesis/discussions/135

**Comment by ReaperAnon** [comment]
What the guy above said, also I wasn't aware there even was a new plugin format. That's really stupid. lol

Older versions of Mutagen would likely be unable to handle a new plugin format, so if it still doesn't work you would want to change the versioning of the patcher to "Latest" instead of "Match" (it should still work on newer version of Mutagen). That should solve your problems.
