### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Guts-Berserker** [ReaperAnon/True-Unleveled-Skyrim#9]
LibGit2Sharp.LibGit2SharpException: failed to read data: The server returned an invalid or unrecognized response

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath)
   at Noggog.GitRepository.CloneRepo.Clone(String repoPath, DirectoryPath localDir)
   at Noggog.GitRepository.CheckOrCloneRepo.Check(GetResponse`1 remote, DirectoryPath localDir, Func`2 isDesirable, CancellationToken cancel)

I'm new to this and Ive no idea what that supposed to mean?

**Comment by ReaperAnon** [comment]
It couldn't grab the actual code from GitHub, I imagine. Never saw someone get that error before, but it's not an issue with the mod.
